#some pseudo API routes
save_step_one:
    path:     api/v1/saveStepOne.json
    defaults: { _controller: MegogoCoreBundle:Api:saveStepOne }

save_step_two:
    path:     api/v1/saveStepTwo.json
    defaults: { _controller: MegogoCoreBundle:Api:saveStepTwo }

get_user:
    path:     api/v1/getUser.json
    defaults: { _controller: MegogoCoreBundle:Api:getUser }

clear_session_data:
    path:     api/v1/clearSessionData.json
    defaults: { _controller: MegogoCoreBundle:Api:clearSession }

step_two:
  path: /stepTwo
  defaults: { _controller: MegogoCoreBundle:Core:stepTwo }

step_three:
  path: /stepThree
  defaults: { _controller: MegogoCoreBundle:Core:stepThree }

get_report:
  path: /api/stream.xml
  defaults: { _controller: MegogoCoreBundle:Api:getReport }


