parameters:
#    megogo_core.example.class: Megogo\CoreBundle\Example

services:
#    megogo_core.example:
#        class: %megogo_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
